// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.AI.Translator.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Job submission batch request
    /// </summary>
    public partial class BatchSubmissionRequest
    {
        /// <summary>
        /// Initializes a new instance of the BatchSubmissionRequest class.
        /// </summary>
        public BatchSubmissionRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BatchSubmissionRequest class.
        /// </summary>
        /// <param name="inputs">The input list of documents or folders
        /// containing documents</param>
        public BatchSubmissionRequest(IList<BatchRequest> inputs)
        {
            Inputs = inputs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the input list of documents or folders containing
        /// documents
        /// </summary>
        [JsonProperty(PropertyName = "inputs")]
        public IList<BatchRequest> Inputs { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Inputs == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Inputs");
            }
            if (Inputs != null)
            {
                foreach (var element in Inputs)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
