// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;
using System.Linq;

namespace Azure.AI.Translator.Models
{
    /// <summary>
    /// This contains an outer error with error code, message, details, target
    /// and an inner error with more descriptive details.
    /// </summary>
    public partial class ErrorV2
    {
        /// <summary>
        /// Initializes a new instance of the ErrorV2 class.
        /// </summary>
        public ErrorV2()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ErrorV2 class.
        /// </summary>
        /// <param name="code">Possible values include: 'InvalidRequest',
        /// 'InvalidArgument', 'InternalServerError', 'ServiceUnavailable',
        /// 'ResourceNotFound', 'Unauthorized', 'RequestRateTooHigh'</param>
        /// <param name="message">Gets high level error message.</param>
        /// <param name="target">Gets the source of the error.
        /// For example it would be "documents" or "document id" in case of
        /// invalid document.</param>
        public ErrorV2(string code = default(string), string message = default(string), string target = default(string), InnerErrorV2 innerError = default(InnerErrorV2))
        {
            Code = code;
            Message = message;
            Target = target;
            InnerError = innerError;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'InvalidRequest',
        /// 'InvalidArgument', 'InternalServerError', 'ServiceUnavailable',
        /// 'ResourceNotFound', 'Unauthorized', 'RequestRateTooHigh'
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// Gets high level error message.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// Gets the source of the error.
        /// For example it would be "documents" or "document id" in case of
        /// invalid document.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerError")]
        public InnerErrorV2 InnerError { get; set; }

    }
}
