// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Microsoft.Rest;
using Newtonsoft.Json;

namespace Azure.AI.Translator.Models
{
    /// <summary>
    /// Job status response
    /// </summary>
    public partial class BatchStatusDetail
    {
        /// <summary>
        /// Initializes a new instance of the BatchStatusDetail class.
        /// </summary>
        public BatchStatusDetail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BatchStatusDetail class.
        /// </summary>
        /// <param name="id">Id of the operation.</param>
        /// <param name="createdDateTimeUtc">Operation created date
        /// time</param>
        /// <param name="lastActionDateTimeUtc">Date time in which the
        /// operation's status has been updated</param>
        /// <param name="status">Possible values include: 'NotStarted',
        /// 'Running', 'Succeeded', 'Failed', 'Cancelled', 'Cancelling'</param>
        public BatchStatusDetail(System.Guid id, System.DateTime createdDateTimeUtc, System.DateTime lastActionDateTimeUtc, StatusSummary summary, string status = default(string))
        {
            Id = id;
            CreatedDateTimeUtc = createdDateTimeUtc;
            LastActionDateTimeUtc = lastActionDateTimeUtc;
            Status = status;
            Summary = summary;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets id of the operation.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets operation created date time
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTimeUtc")]
        public System.DateTime CreatedDateTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets date time in which the operation's status has been
        /// updated
        /// </summary>
        [JsonProperty(PropertyName = "lastActionDateTimeUtc")]
        public System.DateTime LastActionDateTimeUtc { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'NotStarted', 'Running',
        /// 'Succeeded', 'Failed', 'Cancelled', 'Cancelling'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "summary")]
        public StatusSummary Summary { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Summary == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Summary");
            }
        }
    }
}
