// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Azure.AI.Translator.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Document Status Response
    /// </summary>
    public partial class BatchStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the BatchStatusResponse class.
        /// </summary>
        public BatchStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BatchStatusResponse class.
        /// </summary>
        /// <param name="value">The summary status of individual
        /// operation</param>
        /// <param name="nextLink">Url for the next page.  Null if no more
        /// pages available</param>
        public BatchStatusResponse(IList<BatchStatusDetail> value = default(IList<BatchStatusDetail>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the summary status of individual operation
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<BatchStatusDetail> Value { get; set; }

        /// <summary>
        /// Gets or sets url for the next page.  Null if no more pages
        /// available
        /// </summary>
        [JsonProperty(PropertyName = "@nextLink")]
        public string NextLink { get; set; }

    }
}
