// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Azure.AI.Translator.Models
{
    /// <summary>
    /// Document Status Response
    /// </summary>
    public partial class DocumentStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the DocumentStatusResponse class.
        /// </summary>
        public DocumentStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DocumentStatusResponse class.
        /// </summary>
        /// <param name="value">The detail status of individual
        /// documents</param>
        /// <param name="nextLink">Url for the next page.  Null if no more
        /// pages available</param>
        public DocumentStatusResponse(IList<DocumentStatusDetail> value = default(IList<DocumentStatusDetail>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the detail status of individual documents
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<DocumentStatusDetail> Value { get; set; }

        /// <summary>
        /// Gets or sets url for the next page.  Null if no more pages
        /// available
        /// </summary>
        [JsonProperty(PropertyName = "@nextLink")]
        public string NextLink { get; set; }

    }
}
