// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;
using System.Linq;

namespace Azure.AI.Translator.Models
{
    /// <summary>
    /// New Inner Error format which conforms to Cognitive Services API
    /// Guidelines which is available at
    /// https://microsoft.sharepoint.com/%3Aw%3A/t/CognitiveServicesPMO/EUoytcrjuJdKpeOKIK_QRC8BPtUYQpKBi8JsWyeDMRsWlQ?e=CPq8ow.
    /// This contains required properties ErrorCode, message and optional
    /// properties target, details(key value pair), inner error(this can be
    /// nested).
    /// </summary>
    public partial class InnerErrorV2
    {
        /// <summary>
        /// Initializes a new instance of the InnerErrorV2 class.
        /// </summary>
        public InnerErrorV2()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InnerErrorV2 class.
        /// </summary>
        /// <param name="code">Gets detailed error code.</param>
        /// <param name="error">Gets detailed error string.</param>
        /// <param name="message">Gets high level error message.</param>
        /// <param name="target">Gets the source of the error.
        /// For example it would be "documents" or "document id" in case of
        /// invalid document.</param>
        public InnerErrorV2(int? code = default(int?), string error = default(string), string message = default(string), string target = default(string), InnerErrorV2 innerError = default(InnerErrorV2))
        {
            Code = code;
            Error = error;
            Message = message;
            Target = target;
            InnerError = innerError;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets detailed error code.
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; private set; }

        /// <summary>
        /// Gets detailed error string.
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; private set; }

        /// <summary>
        /// Gets high level error message.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; private set; }

        /// <summary>
        /// Gets the source of the error.
        /// For example it would be "documents" or "document id" in case of
        /// invalid document.
        /// </summary>
        [JsonProperty(PropertyName = "target")]
        public string Target { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "innerError")]
        public InnerErrorV2 InnerError { get; set; }

    }
}
